version: '3.3'

services:
        bck-end:
          build: ./api
          ports:
            - 8080:8080
          tty: true
          stdin_open: true
          volumes:
            - ./api:/home/api/
